[manager]
sort_dir_first = true
linemode = "size"
show_hidden = true
show_symlink = true

[preview]
image_filter = "nearest"

[opener]
edit = [
  { run = 'nvim "$@"', block = true }
]
open = [
	{ run = 'zathura "$@"', desc = "Open" },
]
